### ISSUE TITLE
slidingwin and lme4: fixed-effect model matrix is rank deficient so dropping 1 column / coefficient

### ISSUE THREAD

**Issue by akleinhesselink** [LiamDBailey/climwin#13]
I'm having issues getting any lme4 model to run with slidingwin function.   I always get this error when trying to use a glmer or lmer model: 

> Initialising, please wait...
> fixed-effect model matrix is rank deficient so dropping 1 column / coefficient
> Error: Dropping columns failed to produce full column rank design matrix
> In addition: Warning message:
> In qr2rankMatrix(q.r, tol = tol, isBqr = x.dense, do.warn = warn.qr) :
>   qr2rankMatrix(.): QR has negative diag(R) entries

Here's a reproducible example using the Offspring dataset from climwin: 

`library(lme4)`
`library(climwin)`
`###baseline = lmer(Offspring ~ 1 + (1|BirdID), data = Offspring, REML = F) # example from advanced climwin manual`

`data(Offspring)`
`data(OffspringClimate)`

# lmer 
`lmer(Offspring ~ 1 + (1|BirdID), data = Offspring, REML = F) # works`

`slidingwin(xvar = list(Temp = OffspringClimate$Temperature),
                               cdate = OffspringClimate$Date,
                               bdate = Offspring$Date,
                               baseline = lmer(Offspring ~ 1 + (1|BirdID), data = Offspring, REML = F),
                               range = c(150, 0),
                               type = "relative", stat = "mean",
                               func = c("lin"), cmissing = FALSE, cinterval = "day")`

# glmer 
`glmer(Offspring ~ 1 + (1|BirdID), data = Offspring, family = 'poisson') # works`

`OffspringWin_lin <- slidingwin(xvar = list(Temp = OffspringClimate$Temperature),
                               cdate = OffspringClimate$Date,
                               bdate = Offspring$Date,
                               baseline = glmer(Offspring ~ 1 + (1|BirdID), data = Offspring, family = 'poisson'),
                               range = c(150, 0),
                               type = "relative", stat = "mean",
                               func = c("lin"), cmissing = FALSE, cinterval = "day")`

# Session Information: 
via: `sessioninfo()` 

> R version 4.0.2 (2020-06-22)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS  10.16
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] climwin_1.2.3 gridExtra_2.3 ggplot2_3.3.3 lme4_1.1-26   Matrix_1.3-0

**Comment by akleinhesselink** [comment]
I installed the new version of R (4.0.3) and re-installed lme4 and now the slidingwin is now working!  I'm still getting the rank deficiency warning but it is not producing an error that stops the model.  So perhaps something wrong with my previous installation.

**Comment by LiamDBailey** [comment]
Hi Andrew,

Thanks for highlighting the issue. The rank-deficiency warning is new and I'll look into it; however, I don't think this should be affecting the results as it seems to occur before models start to fit.

**Comment by akleinhesselink** [comment]
I think it may have been related to the RccpEigen package on my mac.  I'm getting things to run now.
